Traceback (most recent call last):
  File "c:\Users\Abdul-Qawi\Documents\The Code\python\automating-stuff-with-python\Chapter 11\errorExample.py", line 4, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
